[package]
name = "tgcd"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "=0.1.0-alpha.3"
tokio = "0.2.0-alpha.6"
prost = "0.5.0"
futures-preview = "0.3.0-alpha.19"
bytes = "0.4.12"
tokio-postgres = "0.5.0-alpha.1"
envy = "0.4.0"
serde = { version = "1.0.101", features = ["derive"] }
log = "0.4.8"
thiserror = "1.0.2"
tgcd-proto = { path = "../tgcd-proto" }
blake2b_simd = "0.5.8"
hex = "0.4.0"
