[package]
name = "tgcd"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client", "server"]
client = ["structopt", "serde_json", "rayon", "cfgen", "serde"]
server = ["log", "env_logger", "envy", "serde", "tokio-postgres"]

[dependencies]
tonic = "=0.1.0-alpha.4"
tokio = "0.2.0-alpha.6"
prost = "0.5.0"
futures-preview = "0.3.0-alpha.19"
bytes = "0.4.12"
thiserror = "1.0.2"
blake2b_simd = "0.5.8"
hex = "0.4.0"
tokio-postgres = { version = "0.5.0-alpha.1", optional = true }
envy = { version = "0.4.0", optional = true }
serde = { version = "1.0.101", features = ["derive"], optional = true }
log = { version = "0.4.8", optional = true }
env_logger = { version = "0.7.1", default-features = false, features = ["humantime"], optional = true }
structopt = { version = "0.3.3", optional = true }
rayon = { version = "1.2.0", optional = true }
serde_json = { version = "1.0.41", optional = true }

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "e4eca3f8732f3f286c7184a3e4306e21065c8562"
optional = true

[build-dependencies]
tonic-build = "0.1.0-alpha.4"

[[bin]]
name = "tgcd"
path = "src/bin/server.rs"
required-features = ["server"]

[[bin]]
name = "tgc"
path = "src/bin/client.rs"
required-features = ["client"]
