---
version: "3"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    environment:
      POSTGRES_URL: "postgres://postgres:test@db"
    build: .
    ports:
      - 8080:8080
