---
version: "3"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_up:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
  app:
    depends_on:
      - db_up
    environment:
      POSTGRES_URL: "postgres://postgres:test@db"
    build: .
    ports:
      - 8080:8080
