---
version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
